name: "Lint and typecheck"
on: [push]
  
jobs:
  lint-and-checktype:
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v4
      with:
        node-version: 18
      
    - name: Run install
      run: yarn install --immutable
       
    - name: Lint 
      run: yarn lint:nofix
       
    - name: Type check
      run: yarn typecheck
